### ISSUE TITLE
node-webrtc as a dependency built on travis-ci ubuntu precise 12.04 fails during node-pre-gyp install

### ISSUE THREAD

**Issue by diffalot** [node-webrtc/node-webrtc#253]
as mentioned in #249 is it possible to build node-webrtc on travis-ci  with the .travis.yml:

``` yml
dist: trusty
sudo: true
language: node_js
node_js:
  - "4"
compiler:
  - clang
```

build output: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106873377

note that [`ninja` downloads clang](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106873377#L163), [libwebrtc is successfully built](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106873377#L168), and [the libwebrtc 'release' step is successful](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106873377#L171-L185)

---

but this is less than ideal, because using `sudo: true` prevents open source projects using free travis builds from also using travis' caching mechanism for the `node_modules` folder, so, every build on travis requires building `wrtc` from scratch.

It's not a major, blocking issue, but I'd like to figure out why I can't get travis to build this on ubuntu precise in their container infrastructure.

Below is the troubleshooting I've done.  Perhaps someone with more experience with gyp, node-gyp, depot_tools, ninja, travis and how these tools use environment variables can help me figure out how to make it work.

---

now changing the build so that sudo is set to false:

``` yml
dist: trusty
sudo: false
language: node_js
node_js:
  - "4"
compiler:
  - clang
```

build output show failures: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106881661

because it doesn't actually build on trusty, it builds on precise, which has clang 3.4 installed

---

moving on to use precise, sudo: false, clang-3.6, and g++-4.8 with the instructions from https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements (as suggested in travis-ci/travis-ci#5546)

``` yml
sudo: false
language: node_js
node_js:
  - "4"
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
```

build output shows new errors: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106884568

[clang is successfully downloaded](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106884568#L319), but it is not used to compile libwebrtc, and when libwebrtc is compiled with clang-3.6 the error we get is [`clang: error: unsupported argument '--version' to option 'Xassembler'`](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106884568#L322)

---

so that error leads us to https://bugs.chromium.org/p/webrtc/issues/detail?id=4397 so next build we try it with CC and CXX unset

``` yml
sudo: false
language: node_js
node_js:
  - "4"
compiler: clang-3.6
env:
  - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
install:
  - unset CC
  - unset CXX
  - npm install
```

build output: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106885990

this gives the same error that we first got on precise, that a C++11 compiler is needed

---

why not try making the right clang show up in PATH?

``` yml
sudo: false
language: node_js
node_js:
  - "4"
compiler: clang-3.6
env:
  global:
    - PATH=$HOME/bin:$PATH
    - CXX=clang-3.6
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
install:
  - unset CC
  - unset CXX
  - mkdir $HOME/bin
  - ln -s `which clang-3.6` $HOME/bin/clang
  - ln -s `which clang++-3.6` $HOME/bin/clang++
  - which clang
  - clang -v
  - npm install
```

build output: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106887746

this still gives the same C++11 compiler needed error

---

just for good measure, I've removed the lines that are canceled out later or don't actually do anything, and I added what little debugging I could:

``` yml
language: node_js
node_js:
  - "4"
env:
  global:
    - PATH=$HOME/bin:$PATH
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.6
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.6
      - g++-4.8
install:
  - mkdir -p $HOME/bin
  - ln -s `which clang-3.6` $HOME/bin/clang
  - ln -s `which clang++-3.6` $HOME/bin/clang++
  - which clang
  - which clang++
  - clang -v
  - clang++ -v
  - npm install
```

build output: https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106892314

with the _same_ [C++11 compiler error](https://travis-ci.org/diffalot/travis-test-node-webrtc/builds/106892314#L372-L375)

I have no clue where to go from here, but it seems like ninja must be using system clang 3.4 instead of the clang in $HOME/bin, and I'm not sure why
